### ISSUE TITLE
the page is not loading

### ISSUE THREAD

**Issue by sreeramt30** [felipeall/resumeio-to-pdf#16]
[res](https://resumeio-to-pdf.fly.dev) this link doesn't work anymore. Would you be kind to look into it.

**Comment by felipeall** [comment]
@sreeramt30 It is online again ;) thanks for the heads up

**Comment by sreeramt30** [comment]
The page is up and running, and pasting the link works too. But, it keeps
on loading and never leads to the final preview as it used to before. I've
attached the screenshot for your reference.

**Comment by sreeramt30** [comment]
![Screenshot 2024-05-15 205224](https://github.com/felipeall/resumeio-to-pdf/assets/169893255/bb55cb5d-e383-487b-bd4e-42c38ba3b4b3)

**Comment by sreeramt30** [comment]
Stuck on this

**Comment by sreeramt30** [comment]
Nevermind, my mistake. It works now. Thanks a lot!

**Comment by felipeall** [comment]
@sreeramt30 I believe the number of pages in the resume impacts the processing of it (for example, 3+ pages requires a lot of memory because of OCR and since the app is hosted in a free service it cannot handle it). I increased the host memory by a little bit, could you please try it again?

**Comment by sreeramt30** [comment]
Yes, it works. Sorry for bothering you.
